CREATE TABLE Offer
(
  O_Code INT NOT NULL,
  O_ID INT NOT NULL,
  PRIMARY KEY (O_ID)
);
INSERT INTO Offer VALUES(01,100)
INSERT INTO Offer VALUES(02,500)
INSERT INTO Offer VALUES(03,750)
INSERT INTO Offer VALUES(04,1000)
INSERT INTO Offer VALUES(05,1500)
Select*from Offer
